### ISSUE TITLE
Allow resizing proportions of combat tracker vs chat message panel

### ISSUE THREAD

**Issue by Varriount** [Oromis/foundry-combat-focus#1]
Allow adjusting the amount of space taken up by the combat tracker vs the chat message panel.

**Comment by Oromis** [comment]
Thanks for reporting the suggestion! It would be easiest to provide a dropdown with ratios the user can pick from. Would that be sufficient? What would these ratios be? Suggestion:

Combat Tracker vs Chat Size:

- 1:0
- 4:1
- 3:1
- 5:2
- 1:1
- 2:5
- 1:3
- 1:4

**Comment by Oromis** [comment]
Implemented in 1.1.0. Please reopen if more work needs to go into this :)

**Comment by Varriount** [comment]
@Oromis I was envisioning something more along the lines of how one might resize a window on an operating system - by dragging the edge. This allows quick adjustment to set the ratio to what one desires, depending on the amount of chat vs combat.
Also, I don't believe the repository is configured to allow commenters to reopen issues.

**Comment by Oromis** [comment]
I see. That's more involved though. I hope I get to it in the next few days.

**Comment by Oromis** [comment]
Implemented this in version 1.2.0. It's working quite smoothly :)
