### ISSUE TITLE
Ernie's Modern Layout Incompatiblity

### ISSUE THREAD

**Issue by tjlanza** [Oromis/foundry-combat-focus#11]
Foundry 0.8.6, Combat Focus 1.4.0, EML 0.3.2

With EML enabled, the grab handle is still grabbable (the mouse cursor changes) but it cannot be moved. According to the developer, your module has (had?) explicit compatibility for his module, but they are now out of sync. Please see [the issue on his github](https://github.com/ernieayala/ernies-modern-layout/issues/95).

**Comment by Oromis** [comment]
Ah yeah, I see. I'll update those selectors in the next version :)

**Comment by Oromis** [comment]
Fixed in v1.4.1 :)
