### ISSUE TITLE
1.4.1 showing Version Conflict when Installing

### ISSUE THREAD

**Issue by Shuggaloaf** [Oromis/foundry-combat-focus#12]
<img src= "https://user-images.githubusercontent.com/79543184/124312500-6b9ef680-db3d-11eb-8a86-73dbaac97fba.png" width="50%"/>

I see it lists compatible up to 0.8.8 but throwing this warning on install. Just an FYI.

**Comment by Oromis** [comment]
Thanks, fixed with the latest release! :)
