### ISSUE TITLE
Foundry system version 9 incompatibility

### ISSUE THREAD

**Issue by Spappz** [Oromis/foundry-combat-focus#13]
Module is listed as incompatible with v9.

As far as I know, it does actually work as expected (tested with dnd5e, dnd4eBeta, and pf2e systems), but I'll leave the actual assessment to you.

**Comment by jazz-at-CampTieDye** [comment]
works for me in 9 with 5e.

**Comment by ditzer252** [comment]
Thanks for making this module for Foundry!  It's a real space saver for me.  Please consider bumping up the version compatibility to v9.
The PF2e system is now nagging users that this module is unmaintained and a stability risk.  Thank you.

**Comment by nesretep** [comment]
Foundry v10 is to be released later this week.  It would be nice if you could check compatibility with v10 and update your module.

**Comment by Oromis** [comment]
Thanks and sorry for the delay. The module has been verified to work as-is with both FoundryVTT 9 and 10 and the manifest has been updated accordingly.

**Comment by ditzer252** [comment]
Thanks a lot.  Should I use this mod or https://github.com/Larkinabout/fvtt-combat-chat?  Or are they the same?

**Comment by Larkinabout** [comment]
They're mostly the same, I just made a few tweaks to the styling to shrink some elements on the copy. I can make a pull request here to add those if Oromis is going to be maintaining the original again.
