### ISSUE TITLE
V10 compatibility

### ISSUE THREAD

**Issue by roi007leaf** [Oromis/foundry-combat-focus#16]
Can you please update this module for v10? i really love using it

**Comment by Larkinabout** [comment]
This module should work as is in v10 (only tested in DND5e 2.0.2). I sent Oromis a message today to ask if I can pick up development of this module. Either way, you should be good to use it in v10.

**Comment by Larkinabout** [comment]
I've put up a copy of this module called **[Combat Chat](https://foundryvtt.com/packages/combat-chat)** for Foundry VTT v10.

**Comment by Oromis** [comment]
Hi @Larkinabout! Happy to accept a PR for combat-focus since you seem to have ported it to v10 already!

I'm not using FoundryVTT actively any more (at least for the time being, real life and that stuff...), so I'm definitely happy to see others contribute.
