### ISSUE TITLE
Upper limit for chat log should be set.

### ISSUE THREAD

**Issue by jessev14** [Oromis/foundry-combat-focus#4]
For some reason, sometimes the chat log is expanded all the way to the top of the sidebar, making it appear like the combat tracker has been replaced by the chat log.
The combat tracker can be resized without problem, but an upper limit should be set to prevent this confusion and make it clear that the combat tracker tab always contains both the combat tracker and the chat log.

@enso#0361

![image](https://user-images.githubusercontent.com/68755874/101832376-49904900-3b05-11eb-9868-ddb2439d2a40.png)

**Comment by Oromis** [comment]
Implemented in version 1.2.1. Thanks for reporting!
