### ISSUE TITLE
Combat Tracker to Chat ratio missing

### ISSUE THREAD

**Issue by Th-une** [Oromis/foundry-combat-focus#5]
The chat fills the entire thing, and you cannot change it because the option is missing from Configure Settings

**Comment by Th-une** [comment]
Ok, I discovered it was changed to a drag option. Brilliant!! but also it seems broken to people who don't know!

**Comment by Oromis** [comment]
I see. Do you have a suggestion how it could be made clearer without using up too much vertical space?

**Comment by Th-une** [comment]
Probably have a small note in the options to note that it is now drag to change
