### ISSUE TITLE
Option, remove chat dialog from Combat Tracker

### ISSUE THREAD

**Issue by apoapostolov** [Oromis/foundry-combat-focus#6]
The Chat dialog, when expanded by Polyglot and Dice Calculator mods, can take a lot of space best reserved for the chat itself.

Please add an option that removes the chat dialog from the chat tab content injected in Combat Tracker.

![image](https://user-images.githubusercontent.com/4083812/101932325-48cde480-3be3-11eb-98ce-2eecd93c60e8.png)

**Comment by Oromis** [comment]
Great input, thanks. Will implement :)

**Comment by Oromis** [comment]
Added in version 1.3.0. Thanks for suggesting this feature!

**Comment by apoapostolov** [comment]
Thank you!
