### ISSUE TITLE
Chat area taking too much space

### ISSUE THREAD

**Issue by Darkiller25** [Oromis/foundry-combat-focus#8]
Hi!

First off, thanks for this module! It's really usesful, but I've been having an issue with it (if it's considered an issue) where the chat area takes way too much space compared to the combat tracker.

![Combat_Focus](https://user-images.githubusercontent.com/71094682/103584493-6a9f4c00-4eaf-11eb-8791-20c21f71d093.png)

I don't know if it's because of another module I have installed, but nothing is supposed to mess with the combat tracker as far as I know.

**Comment by Darkiller25** [comment]
Nevermind! I was being stupid and didn't see the line that allows me to make it bigger or smaller :P

**Comment by Oromis** [comment]
Sorry for not responding earlier. Yes, that what I would have suggested :D 

Indeed there's a bug somewhere that makes the chat area too big without user interaction - I'll track this down and fix it.
