### ISSUE TITLE
Combat Focus issue

### ISSUE THREAD

**Issue by Tam1974** [Oromis/foundry-combat-focus#9]
Love Combat Focus, but the Right Click menu does not work in the bottom half of your Encounter/Chat tab, (it still works in the Main Chat tab). For example, I start an encounter, role, and the results appear in the same Encounter Tab, (thanks to Combat Focus), but when I try to apply damage, ie Right Click in the Chat, and choose Apply Damage - that Right Click Menu does not appear/work.
Hard to explain - but I hope you get the gist.

Many thanks

**Comment by Oromis** [comment]
I'll close this as I cannot reproduce it. Feel free to reopen if this is still an issue.
